force-app/main/default/objects/Trekking_Event__c/Trekking_Event__c.object-meta.xml
<CustomObject>
    <label>Trekking Event</label>
    <nameField>
        <label>Trekking Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trekking Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trekking_Event__c/fields/Event_slot__c.field-meta.xml
<CustomField>
    <fullName>Event_slot__c</fullName>
    <label>Event slot</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trekking_Event__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SSS_TrekkingEventTriggerHandler.cls
public without sharing class SSS_TrekkingEventTriggerHandler {

    public static void runBeforeTrigger(){
        
        if(Trigger.isInsert){
            updateEventSlot(Trigger.new);
        }
        
    }
    
    public static void updateEventSlot(List<Trekking_Event__c> trekkingEvents){
        
        for(Trekking_Event__c event : trekkingEvents){
            
            event.Event_slot__c = SSS_Utility.calculateWeekendNumber(event.Start_time__c);
            
        }
        
    }
    
}