force-app/main/default/objects/Destination__c/Destination__c.object-meta.xml
<CustomObject>
    <label>Destination</label>
    <nameField>
        <displayFormat>D-{0000}</displayFormat>
        <label>Destination Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Destinations</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Destination__c/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <label>Location</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Locations</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Destination__c/fields/Trekking_Event__c.field-meta.xml
<CustomField>
    <fullName>Trekking_Event__c</fullName>
    <label>Trekking Event</label>
    <referenceTo>Trekking_Event__c</referenceTo>
    <relationshipLabel>Destinations</relationshipLabel>
    <relationshipName>Destinations</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <reparentableMasterDetail>true</reparentableMasterDetail>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Destination__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Beach</fullName>
            </value>
            <value>
                <fullName>Fort</fullName>
            </value>
            <value>
                <fullName>Ghats</fullName>
            </value>
            <value>
                <fullName>Jungle Trail</fullName>
            </value>
            <value>
                <fullName>Peak</fullName>
            </value>
            <value>
                <fullName>Waterfall</fullName>
            </value>
            <value>
                <fullName>Valley</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Destination__c/fields/Visiting_Date__c.field-meta.xml
<CustomField>
    <fullName>Visiting_Date__c</fullName>
    <label>Visiting Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Trekking_Event__c/Trekking_Event__c.object-meta.xml
<CustomObject>
    <label>Trekking Event</label>
    <nameField>
        <label>Trekking Event Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Trekking Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Trekking_Event__c/fields/Event_slot__c.field-meta.xml
<CustomField>
    <fullName>Event_slot__c</fullName>
    <label>Event slot</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Trekking_Event__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>Grade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Easy</fullName>
            </value>
            <value>
                <fullName>Moderate</fullName>
            </value>
            <value>
                <fullName>Difficult</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Trekking_Event__c/fields/Organization__c.field-meta.xml
<CustomField>
    <fullName>Organization__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Organization</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Trekking Events</relationshipLabel>
    <relationshipName>Trekking_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Trekking_Event__c/fields/Start_time__c.field-meta.xml
<CustomField>
    <fullName>Start_time__c</fullName>
    <label>Start time</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/SSS_EventHomeController.cls
public class SSS_EventHomeController {
    
    private static Map<Integer, String> monthMap = new Map<Integer, String>{
    	1 => 'Jan',  
        2 => 'Feb',  
        3 => 'Mar',  
        4 => 'Apr',  
        5 => 'May',  
        6 => 'June',  
        7 => 'July',  
        8 => 'Aug',  
        9 => 'Sept',  
        10 => 'Oct',  
        11 => 'Nov',  
        12 => 'Dec'    
    };
    
    @AuraEnabled
    public static EventHomeDTO fetchEventDetails(){
        
        EventHomeDTO eventDetails = new EventHomeDTO();
        
        List<Trekking_Event__c> trekkingEvents = [SELECT id, name, Organization__r.name, Event_slot__c, 
                                                  Start_time__c, End_Time__c, Grade__c, Batch_Size__c, 
                                                  	(SELECT id, Location__c, Type__c, Visiting_Date__c 
                                                     FROM Destinations__r) 
                                                  FROM Trekking_Event__c];
        
        eventDetails.weekendWiseTrekEvents = prepareWeekendWiseTrekEvents(trekkingEvents);
        
        return eventDetails;
        
    }
    
    private static Map<String, List<TrekEventsDTO>> prepareWeekendWiseTrekEvents(List<Trekking_Event__c> trekkingEvents){

        Map<String, List<TrekEventsDTO>> weekendWiseTrekEvents = new Map<String, List<TrekEventsDTO>>();
        
        for(Trekking_Event__c trekEvent : trekkingEvents){
            
            TrekEventsDTO trekEventDetails = new TrekEventsDTO();
            trekEventDetails.eventName = trekEvent.name;
            trekEventDetails.organizationName = trekEvent.Organization__r.Name;
            trekEventDetails.eventDate = getEventDate(trekEvent.Start_time__c, trekEvent.End_Time__c);
            trekEventDetails.batchSize = (Integer) trekEvent.Batch_Size__c;
            trekEventDetails.destinations = getEventDestinations(trekEvent.Destinations__r);
            
            String weekendSlot = trekEvent.Event_slot__c + ' ' + trekEvent.End_Time__c.year();
            if(weekendWiseTrekEvents.get(weekendSlot) != null){
                weekendWiseTrekEvents.get(weekendSlot).add(trekEventDetails);
            }else{
                weekendWiseTrekEvents.put(weekendSlot, new List<TrekEventsDTO>{trekEventDetails});
            }
            
        }
        
        return weekendWiseTrekEvents;
    
    }
    
    private static List<DestinationDTO> getEventDestinations(List<Destination__c> destinationRecs){
        
        List<DestinationDTO> destinations = new List<DestinationDTO>();
        for(Destination__c destinationRec : destinationRecs){
            
            DestinationDTO destination = new DestinationDTO();
            destination.name = destinationRec.Location__c;
            destination.visitDate = destinationRec.Visiting_Date__c.format('EEE, MMM d yyyy');
            destination.destinationType = destinationRec.Type__c;
            
            destinations.add(destination);
            
        }
        
        return destinations;
        
    }
    
    private static String getEventDate(DateTime startTime, DateTime endTime){
        
        String eventDate = '';
        eventDate = startTime.day() + ' - ' + endTime.day() + ' ' + monthMap.get(startTime.month()) + ', ' + endTime.year();
        
        return eventDate;
    }

    public class EventHomeDTO{
        
        @AuraEnabled
        public Map<String, List<TrekEventsDTO>> weekendWiseTrekEvents; 
        
    }
    
    public class TrekEventsDTO{
        
        @AuraEnabled
        public String eventName;
        
        @AuraEnabled
        public String organizationName;
        
        @AuraEnabled
        public String eventDate;
        
        @AuraEnabled
        public Integer batchSize;
        
        @AuraEnabled
        public List<DestinationDTO> destinations;
        
    }
    
    public class DestinationDTO{
        
        @AuraEnabled
        public String name;
        
        @AuraEnabled
        public String visitDate;
        
        @AuraEnabled
        public String destinationType;
        
    }
    
}